---
abstract: 'Detect if warnings have been left at defaults'
author:
  - 'haarg - Graham Knop (cpan:HAARG) <haarg@haarg.org>'
build_requires:
  Test::More: 0
configure_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-DefaultWarnings
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006001
resources:
  IRC: irc://irc.perl.org/#toolchain
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Devel-DefaultWarnings
  license: http://dev.perl.org/licenses/
  repository: git://github.com/haarg/Devel-DefaultWarnings
version: 0.001000
